### ISSUE TITLE
Expand/Collapse buttons missing next to Unified Inbox sections

### ISSUE THREAD

**Issue by orky** [edipox/n1-ido#11]
The Nylas N1 default themes of Light/Dark have carets visible that allow you to collapse & expand folders relating to Unified Inbox such as Inbox, Starred, Sent, All Mail, Trash, & Drafts.

![image](https://cloud.githubusercontent.com/assets/1643567/13125681/cd79e9be-d57b-11e5-9b02-30e01fc0aea3.png)

![image](https://cloud.githubusercontent.com/assets/1643567/13125692/e287cdd0-d57b-11e5-8809-141b126b65d0.png)

**Comment by edipox** [comment]
@orky thank you for reporting those issues, I will release fixes soon

**Comment by michalkopanski** [comment]
:+1: @edipox, feel free to assign an issue to me if you want.

**Comment by edipox** [comment]
@michalkopanski thank you, then I will assign you this one
