### ISSUE TITLE
Security w/ Nylas?

### ISSUE THREAD

**Issue by oldhickory30** [edipox/n1-ido#17]
I have read much on the web regarding the fact that my email is going through a 3rd party server when using Nylas, is this correct/ If so, what guarantees my privacy and security?

**Comment by michalkopanski** [comment]
Hi @oldhickory30, you may want to ask this question in https://github.com/nylas/N1.

This repo is just a theme for the Nylas N1 email client.

**Comment by edipox** [comment]
Yeah thank you @michalkopanski
