### ISSUE TITLE
Updates on the accounts sidebar show as white

### ISSUE THREAD

**Issue by jackiehluo** [edipox/n1-ido#2]
<img width="177" alt="screen shot 2016-01-22 at 4 25 09 pm" src="https://cloud.githubusercontent.com/assets/8452682/12526679/d2dc6640-c124-11e5-9622-786bf42199e8.png">

Might be good to change that background/foreground to match! I'll try to take a look this weekend, too, but otherwise really loving this theme!

**Comment by edipox** [comment]
@jackiehluo thank you! Any help will be very wellcome. I won't work this weekend (sunday is my birthday :tada: ) but the next week I'll be back.

**Comment by edipox** [comment]
@jackiehluo Now it seems to be working. I also fixed an issue when dropping items on labels. And the preferences page now looks much better

**Comment by jackiehluo** [comment]
Hm, not sure if it changed for me. How does it look on your version?

**Comment by edipox** [comment]
@jackiehluo 
Like this:
![account-sync](https://cloud.githubusercontent.com/assets/1580541/12611622/7ec1f72c-c4cc-11e5-87e8-9ad6af48c62d.jpg)

But to get the theme updated I've removed it (from .nylas/packages/) and reinstalled it. I don't know if there is another way to update N1 themes.

**Comment by michalkopanski** [comment]
@edipox @jackiehluo I cloned my repo directly into the `~/.nylas/packages` directory, and then just `Developer > Reload` or `Option + Command + L` to reload the changes.
