### ISSUE TITLE
No hover style when dragging emails to folder

### ISSUE THREAD

**Issue by midudev** [edipox/n1-ido#20]
Versión 0.4.19-d41e72c (0.4.19-d41e72c)
OSX 10.11.4

Hi! First of all, amazing theme. :+1: Best one I've seen so far. Now, while the theme is gorgeous, there's a lack of hover when a user drag emails hover a folder on the sidebar.

In the following image you can see the INBOX.Trash selected and trying to drag emails  to any folder is not producing a hover style.

<img width="230" alt="captura de pantalla 2016-04-04 12 36 23" src="https://cloud.githubusercontent.com/assets/1561955/14245500/210d84e0-fa62-11e5-8fc9-bf6879427eb8.png">

**Comment by edipox** [comment]
Issue confirmed. Thank you @miduga
