### ISSUE TITLE
Fix style issues for 0.4.32

### ISSUE THREAD

**Issue by edipox** [edipox/n1-ido#23]
- This button is almost invisible: 
  ![screen shot 2016-05-03 at 11 45 21 am](https://cloud.githubusercontent.com/assets/1580541/14989244/db7fb1d0-1124-11e6-8768-83979360506a.png)
- Compose windows buttons:

![screen shot 2016-05-03 at 11 46 44 am](https://cloud.githubusercontent.com/assets/1580541/14989256/e43ce112-1124-11e6-95cb-892f507383e4.png)

**Comment by madeleineostoja** [comment]
also (for me at least) the composer window: 
<img width="805" alt="screen shot 2016-05-04 at 12 25 26 pm" src="https://cloud.githubusercontent.com/assets/6374876/15003826/5a87eea6-11f3-11e6-94b7-5fe3f774b540.png">

**Comment by edipox** [comment]
I don't know how I didn't noticed that. Thank you @seaneking

**Comment by edipox** [comment]
Everything seems to be working now
