### ISSUE TITLE
change the theme 

### ISSUE THREAD

**Issue by zhaoyuxuan** [edipox/n1-ido#26]
I just install the theme u provided, and somehow, i can't change the default theme to skyfall. how should I do that?

**Comment by edipox** [comment]
Hi @zhaoyuxuan I'll make a little video showing how to do that in macOS 🙂

**Comment by edipox** [comment]
@zhaoyuxuan Here is the video url: https://youtu.be/4L2v6tuAonE
I couldn't properly edit it. Please let me know if it is clear enough
