### ISSUE TITLE
N1 v0.4.5 sidebar style doesn't take full height

### ISSUE THREAD

**Issue by brandon099** [edipox/n1-ido#6]
Just upgraded N1 and running the latest n1-ido, and the account-sidebar styling doesn't take up the full height vertically. I should note, this is on a HiDPI screen (2560x1440), and I've removed any personally identifiable information. I should also mention that the dark background goes until the folders list ends, then it is white.
![02-06-2016-slop4789](https://cloud.githubusercontent.com/assets/1628223/12898928/57f7cf3c-ce6c-11e5-8dc4-b7425e7cc6c0.png)

**Comment by brandon099** [comment]
It looks like PR #5 might already address this, sorry I missed that!

**Comment by michalkopanski** [comment]
Hey @brandon099, yea that's taken care of in my PR.

**Comment by edipox** [comment]
@brandon099 I merged @michalkopanski's PR with some extra code
